### ISSUE TITLE
Error: package or namespace load failed for ‘QuantumClone’ 

### ISSUE THREAD

**Issue by andhena** [DeveauP/QuantumClone#1]
Dear Paul,
I would like to use QuantumClone but I'm experiencing troubles with making it work.
Indeed when I do: 
`> install.packages("QuantumClone")`
There is no error but once I try to load it using
`> library(QuantumClone)`
Then I got this error
`Error: package or namespace load failed for ‘QuantumClone’ in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called ‘robustbase’`
I've tried to download `robustbase` independently but the error is persisting.
Coud you please help me with this problem?
Thank you in advance,
Kind regards, -Charlotte

NB: I'm using R version 3.4.4

**Comment by DeveauP** [comment]
Hi Charlotte,

Are you running on Unix or Windows?
I tried to reproduce on Windows 8, R 3.5.0 with the CRAN and Github versions but could not get your error.

Can you check that `robustbase` is installed correctly? (either with `find.package("robustbase")` or by loading it with `library(robustbase)` ). Could you do the same for `fpc` too?

`fpc` imports `robustbase` to initialize cluster centers, if you use the k-medoid initialization. A quick fix would be to move to `fpc`to suggested packages and not imports, but would not directly solve your issue.

Best wishes,

**Comment by andhena** [comment]
Hi Paul,
I'm using Mac OS X (El Capitan, v 10.11.5) and I guess that's why it's not working.
I've made some research and found an interesting discussion so I'm gonna share it here in case someone using a Mac has a similar problem :
https://stackoverflow.com/questions/23916219/os-x-package-installation-depends-on-gfortran-4-8

But it didn't work for me so I used **biocLite** instead:
```
source("https://bioconductor.org/biocLite.R")
biocLite()
biocLite("robustbase")
biocLite("kernlab")
```

I never experienced that kind of troubles installing R packages but at least now it's working! 
Thanks for the guidance, 
-Charlotte
