### ISSUE TITLE
QuantumClone could be used for targeted panel sequencing data?

### ISSUE THREAD

**Issue by Tato14** [DeveauP/QuantumClone#3]
Hi,
I see in your documentation that QuantumClone can use WES and WGS data. Is it possible to use also targeted panel data?
Thanks!

**Comment by DeveauP** [comment]
Hello,

QuantumClone has not been validated with targeted sequencing. It could work if you provide the copy number alterations or if you know that your profile is fully diploid.

The issue may also be that the statistical model behind QuantumClone may not represent very well targeted data, by being overconfident.

Best wishes,
Paul
