### ISSUE TITLE
How to get the "Genotype" for input files?

### ISSUE THREAD

**Issue by b-niu** [DeveauP/QuantumClone#4]
Dear author, 

Sorry for this question. I have noticed that in the paper you published, it is said that
>In order to validate QuantumClone on rearranged or hyper-diploid genomes, we simulated variants in loci of genotype AB, AAB, AABB and in a nearly diploid genome, where all possible genotypes can be observed (Fig. 2). 

So I guess that the genotype is describing the copy numbers and haplotypes of somatic mutations. 

1. But what is the meaning of "A" and "B"? 
2. Are "A" and "B" having relationship with major and minor allele frequencies?
3. A site with 4 copies might be "AAAB", "AABB", "ABBB",  "AAAA", and "BBBB"?
4. Some software can give sites with 1 copy. They should be "A" or "B"?
5. How about sites with  0 copy?
6. Can you suggest some softwares to generate the "Genotype" atrributes?

Thanks a lot. 
Best regards.

**Comment by DeveauP** [comment]
Hello,

1 & 2. A & B are the major and minor allele respectively. So a genotype AB is what you expect for normal cells. AA means loss of heterozygosity, ....
3. From the previous answer, only AAAA, AAAB and AABB are possible at the 4 copy level
4. They should all be A
5. 0 copy should mean that the portion has been deleted except for non-cancer cells
6. In the publication we used FREEC ( http://boevalab.com/FREEC/ ). I guess that there are now numerous possibilities to do so. It should also provide and estimate of purity to correct for contamination by normal cells in the samples.

Hope this helps.
Best wishes,
Paul DEVEAU

**Comment by b-niu** [comment]
Thanks a lot @DeveauP !

Forgive me for one more question: 
Do you have any suggestion about the software to estimate purity ?

**Comment by DeveauP** [comment]
Delayed answer here.

We originally estimated the purity with Control-FREEC, I don't know what is SOTA currently.
