### ISSUE TITLE
Information about individual mutations in clonal tree

### ISSUE THREAD

**Issue by kdhingra307** [DeveauP/QuantumClone#6]
Hi,

I am new to Clonal evolution(so please pardon me if my doubt is naive). I have tried Clonefinder, MixPhy, and QuantumClone. With Clonefinder, and MixPhy I was able to get individual SNV's mutation for each node of the tree (like AATTAAA) but with QuantumClone I am getting cellularity at the cluster level. Is this by design or am I missing something?

**Comment by DeveauP** [comment]
Hi Karan,

Clonefinder and MixPhy seem to be more recent than QuantumClone. QuantumClone was created with the same philosophy as sciClone or pyClone, that means without a tree like structure imposed on the different clusters, so you are not missing anything there. 

There were some attempts to create a phylogenetic tree based on the clusters found, but the conditions we imposed on the tree were too strict.
